### ISSUE TITLE
rouge may not do its best

### ISSUE THREAD

**Issue by szepeviktor** [PrinsFrank/PrinsFrank.nl#32]
**Describe the bug**

It looks like this.

![image](https://github.com/PrinsFrank/PrinsFrank.nl/assets/952007/f5e7ca36-8a38-4327-a1df-ec29e155ab84)

**Comment by PrinsFrank** [comment]
@szepeviktor I've finally come around to this: I'm relying on two different rougify styles for light an dark mode. What do you think?

**Comment by szepeviktor** [comment]
Fixed in d271a57
Yes, now I can read the code block.
